# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t bharathraam/userservice .
    - name: publish image to docker hub
      run: docker push bharathraam/userservice:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull docker image from docker hub
        run: sudo docker pull bharathraam/userservice:latest
      - name: delete old container
        run: sudo docker rm -f userservice-container
      - name: run docker container
        run: sudo docker run -d -p 8080:8080 --name userservice-container bharathraam/userservice
